- hosts: localhost
  roles:
  - role: openmicroscopy.omego
  - role: openmicroscopy.omero-python-deps
  - role: openmicroscopy.ice
  vars:
  - ice_version: "3.6"
    ice_python_wheel: https://github.com/openmicroscopy/zeroc-ice-py-centos7/releases/download/0.0.3/zeroc_ice-3.6.4-cp27-cp27mu-linux_x86_64.whl
